name: PR Apporval Validator

on:
  pull_request_review:
    types: [submitted]
    branches: ["main"]

jobs:
  pr-approval:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: validate
        run: |
          node src\test.js
